feat: sharing buckets
dokedu/frontend pull request #27
Opened 2023-08-17 19:09 UTC by benciks

2023-08-17 19:41 UTC, tomhaerter requested changes
Looks great! I'll check it out locally and do a deeper review

2023-08-17 19:41 UTC, tomhaerter commented on src/components/d-context-menu/d-context-menu.vue
> +        console.log(instanceBounds);
```suggestion
```

2023-08-17 19:41 UTC, tomhaerter commented on src/components/drive/DDialogShareDrive.vue
> +    mutation editShare($input: CreateShareInput!) {
Why is it also called `CreateShareInput`? Same thing in the backend because it has the same fields?

2023-08-17 19:41 UTC, tomhaerter commented on src/components/drive/DDialogShareDrive.vue
> +const onCreateShare = async (id: string) => {
I **personally** prefer to write "normal" functions instead of arrow functions in Vue setup components

2023-08-18 08:34 UTC, benciks commented on src/components/drive/DDialogShareDrive.vue
> +    mutation editShare($input: CreateShareInput!) {
Yes, same thing, same fields.

2023-08-22 12:31 UTC, merged